
NAME= texture

CC  = cl -c -W3 -Zi -GX -Oxwt -DSTRICT -DWIN32 -D_WIN32
LINK= link -map -pdb:none -debug:full -debugtype:cv -out:$(NAME).exe -subsystem:windows
DEF =-DDEBUG -DSTRICT
RC  = rc

OBJ  = $(NAME).obj dumb3d.obj \
			divflfl.obj \
			divfxfl.obj \
			subafxfl.obj \
			divifl.obj

LIBS = gdi32.lib user32.lib comdlg32.lib

.cpp.obj:
        $(CC) /Fo$*.obj /Fl$*.lst $< 

goal: $(NAME).exe

$(NAME).exe: $(OBJ) $(NAME).res makefile
        $(LINK) $(OBJ) $(LIBS) $(NAME).res

$(NAME).res: $(NAME).rc $(NAME).ico
        $(RC) -r $(NAME).rc

clean:
        del $(NAME).exe
		del *.lst
        del *.res
        del *.err
        del *.obj
        del *.map
        del *.sym
        del *.cod
        del *.pdb

