/*

This material is Copyright 1995, 1996 Chris Hecker, All Rights Reserved.
It's for you to read and learn from, not to put in your own articles
or books or on your website, etc.  Thank you.

Chris Hecker
checker@netcom.com

*/

/* Menu Items */
#define MENU_ABOUT		0
#define MENU_EXIT		1
#define MENU_ANIMATE	2
#define MENU_TIME		3
#define MENU_TEST		4

#define MENU_MAPPER		10
#define MENU_VIEW		50

