//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Fate.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_FATETYPE                    129
#define IDD_SECTOR_ATTR                 130
#define IDC_CEIL                        1000
#define IDC_FLOOR                       1001
#define IDC_NUMBER                      1002
#define IDC_EDGECNT                     1003
#define IDC_CEIL_TEX                    1004
#define IDC_FLOORTEX                    1005
#define IDC_CEIL_SEL                    1006
#define IDC_FLOOR_SEL                   1007
#define ID_OPTIONS_GRIDUP               32771
#define ID_OPTIONS_GRID_DOWN            32772
#define ID_OPTIONS_ZOOMIN               32773
#define ID_OPTIONS_ZOOMOUT              32774
#define ID_INDICATOR_GRID               32775
#define ID_INDICATOR_SC2                32776
#define ID_INDICATOR_SNAP               32777
#define ID_INDICATOR_INFO               32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32778
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
