//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Kine.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_SETROTATE                   130
#define IDC_XAXIS                       1000
#define IDC_YAXIS                       1001
#define IDC_ZAXIS                       1002
#define ID_VIEW_GEOMETRY                32771
#define ID_VIEW_USEQUATERNIONS          32772
#define ID_HELP_WHICHOPENGL             32774
#define ID_INDICATOR_ROT2               59142
#define ID_INDICATOR_QUAT               59143
#define ID_INDICATOR_ROT                59144
#define ID_INDICATOR_LOWROT             59144
#define ID_INDICATOR_STATUS             59145
#define ID_INDICATOR_UPROT              59145

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
